env:
  IMAGE_TAG: unstable
  PLATFORMS: linux/amd64,linux/arm64
jobs:
  build:
    if: ${{ github.repository_owner == 'IQSS' }}
    name: Build image
    permissions:
      contents: read
      packages: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Build base container image with local architecture
      run: mvn -f modules/container-base -Pct package
    - continue-on-error: true
      if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
      name: Push description to DockerHub
      uses: peter-evans/dockerhub-description@v3
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        readme-filepath: ./modules/container-base/README.md
        repository: gdcc/base
        short-description: Dataverse Base Container image providing Payara application
          server and optimized configuration
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - continue-on-error: true
      if: ${{ github.event_name != 'pull_request' }}
      name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - continue-on-error: true
      if: ${{ github.event_name != 'pull_request' }}
      name: Set up QEMU for multi-arch builds
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      if: ${{ github.ref_name == 'master' }}
      name: Re-set image tag based on branch
      run: echo "IMAGE_TAG=alpha" >> $GITHUB_ENV
    - continue-on-error: true
      if: ${{ github.event_name != 'pull_request' }}
      name: Deploy multi-arch base container image to Docker Hub
      run: mvn -f modules/container-base -Pct deploy -Dbase.image.tag=${{ env.IMAGE_TAG
        }} -Ddocker.platforms=${{ env.PLATFORMS }}
    strategy:
      matrix:
        jdk:
        - '17'
  push-app-img:
    if: ${{ github.event_name != 'pull_request' }}
    name: Rebase & Publish App Image
    needs: build
    permissions:
      contents: read
      packages: write
      pull-requests: write
    secrets: inherit
    uses: ./.github/workflows/container_app_push.yml
name: Base Container Image
on:
  repository_dispatch:
    types: trigger-ga___container_base_push.yml
