env:
  BASE_IMAGE_TAG: unstable
  IMAGE_TAG: unstable
  PLATFORMS: linux/amd64,linux/arm64
jobs:
  deploy:
    if: ${{ github.repository_owner == 'IQSS' }}
    name: Package & Push
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: refs/pull/${{ github.event.client_payload.pull_request.number }}/merge
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.GHCR_TOKEN }}
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
    - continue-on-error: true
      name: Set up QEMU for multi-arch builds
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      name: Set image tag to branch name
      run: 'echo "IMAGE_TAG=$(echo "${{ github.event.client_payload.pull_request.head.ref
        }}" | tr ''\\/_:&+,;#*'' ''-'')" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Build app and configbaker container image with local architecture and
        submodules (profile will skip tests)
      run: 'mvn -B -f modules/dataverse-parent -P ct -pl edu.harvard.iq:dataverse
        -am install

        '
    - continue-on-error: true
      name: Deploy multi-arch application and configbaker container image
      run: 'mvn  -Dapp.image.tag=${{ env.IMAGE_TAG }} -Dbase.image.tag=${{ env.BASE_IMAGE_TAG
        }} -Ddocker.registry=ghcr.io -Ddocker.platforms=${{ env.PLATFORMS }} -Pct
        deploy

        '
    - continue-on-error: true
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: registry-push
        hide_and_recreate: true
        hide_classify: OUTDATED
        message: ':package: Pushed preview images as

          ```

          ghcr.io/gdcc/dataverse:${{ env.IMAGE_TAG }}

          ```

          ```

          ghcr.io/gdcc/configbaker:${{ env.IMAGE_TAG }}

          ```

          :ship: [See on GHCR](https://github.com/orgs/gdcc/packages/container). Use
          by referencing with full name as printed above, mind the registry name.

          '
        number: ${{ github.event.client_payload.pull_request.number }}
    - continue-on-error: true
      if: ${{ failure() }}
      uses: peter-evans/create-or-update-comment@v3
      with:
        body: ':package: Could not push preview images :disappointed:. See [log](https://github.com/IQSS/dataverse/actions/runs/${{
          github.run_id }}) for details.

          '
        issue-number: ${{ github.event.client_payload.pull_request.number }}
name: Preview Application Container Image
on:
  repository_dispatch:
    types: trigger-ga___container_app_pr.yml
