jobs:
  docs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: OdumInstitute/sphinx-action@master
      with:
        docs-folder: doc/sphinx-guides/
name: Guides Build Status
on:
  repository_dispatch:
    types: trigger-ga___guides_build_sphinx.yml
