jobs:
  coverage-report:
    name: Coverage Report Submission
    needs: integration-test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: java-reportdir
    - continue-on-error: true
      run: tar -xvf java-reportdir.tar
    - continue-on-error: true
      env:
        CI_NAME: github
        COVERALLS_SECRET: ${{ secrets.GITHUB_TOKEN }}
      name: Deposit Code Coverage
      run: 'mvn -B -DrepoToken=${COVERALLS_SECRET} -DpullRequest=${{ github.event.number
        }} jacoco:report coveralls:report

        '
  integration-test:
    continue-on-error: ${{ matrix.experimental }}
    name: (${{ matrix.status}} / JDK ${{ matrix.jdk }}) Integration Tests
    needs: unittest
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: java-artifacts
    - continue-on-error: true
      run: 'tar -xvf java-builddir.tar

        tar -xvf java-m2-selection.tar -C /

        '
    - continue-on-error: true
      run: mvn -DskipUnitTests -Dtarget.java.version=${{ matrix.jdk }} verify
    - continue-on-error: true
      run: tar -cvf java-reportdir.tar target/site
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: java-reportdir
        path: java-reportdir.tar
        retention-days: 3
    strategy:
      fail-fast: false
      matrix:
        experimental:
        - false
        jdk:
        - '17'
        status:
        - Stable
  push-app-img:
    name: Publish App Image
    needs: integration-test
    permissions:
      contents: read
      packages: write
      pull-requests: write
    secrets: inherit
    uses: ./.github/workflows/container_app_push.yml
  unittest:
    continue-on-error: ${{ matrix.experimental }}
    name: (${{ matrix.status}} / JDK ${{ matrix.jdk }}) Unit Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Build with Maven and run unit tests
      run: 'mvn -B -f modules/dataverse-parent -Dtarget.java.version=${{ matrix.jdk
        }} -DcompilerArgument=-Xlint:unchecked -P all-unit-tests -DskipIntegrationTests
        -pl edu.harvard.iq:dataverse -am install

        '
    - continue-on-error: true
      run: rm -rf ~/.m2/repository/edu/harvard/iq/dataverse
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: dataverse-java${{ matrix.jdk }}.war
        path: target/dataverse*.war
        retention-days: 7
    - continue-on-error: true
      run: 'tar -cvf java-builddir.tar target

        tar -cvf java-m2-selection.tar ~/.m2/repository/io/gdcc/dataverse-*

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: java-artifacts
        path: 'java-builddir.tar

          java-m2-selection.tar

          '
        retention-days: 3
    strategy:
      fail-fast: false
      matrix:
        experimental:
        - false
        jdk:
        - '17'
        status:
        - Stable
name: Maven Tests
on:
  repository_dispatch:
    types: trigger-ga___maven_unit_test.yml
