jobs:
  dispatch:
    if: ${{ github.repository_owner == 'IQSS' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Dispatch
      uses: peter-evans/slash-command-dispatch@v3
      with:
        commands: 'push-image

          '
        permission: write
        repository: IQSS/dataverse
        token: ${{ secrets.GHCR_TOKEN }}
name: PR Comment Commands
on:
  repository_dispatch:
    types: trigger-ga___pr_comment_commands.yml
