jobs:
  checkstyle_job:
    name: Checkstyle job
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        checkstyle_config: checkstyle.xml
        fail_on_error: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
name: Maven CheckStyle Task
on:
  repository_dispatch:
    types: trigger-ga___reviewdog_checkstyle.yml
