env:
  SHELLSPEC_VERSION: 0.28.1
jobs:
  shellspec-centos7:
    container:
      image: centos:7
    name: CentOS 7
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Install shellspec
      run: 'curl -fsSL https://github.com/shellspec/shellspec/releases/download/${{
        env.SHELLSPEC_VERSION }}/shellspec-dist.tar.gz | tar -xz -C /usr/share

        ln -s /usr/share/shellspec/shellspec /usr/bin/shellspec

        '
    - continue-on-error: true
      name: Install dependencies
      run: yum install -y ed
    - continue-on-error: true
      name: Run shellspec
      run: 'cd tests/shell

        shellspec

        '
  shellspec-macos:
    name: MacOS
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install shellspec
      run: curl -fsSL https://git.io/shellspec | sh -s 0.28.1 --yes
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Run Shellspec
      run: 'cd tests/shell

        /Users/runner/.local/bin/shellspec

        '
  shellspec-rocky8:
    container:
      image: rockylinux/rockylinux:8
    name: RockyLinux 8
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Install shellspec
      run: 'curl -fsSL https://github.com/shellspec/shellspec/releases/download/${{
        env.SHELLSPEC_VERSION }}/shellspec-dist.tar.gz | tar -xz -C /usr/share

        ln -s /usr/share/shellspec/shellspec /usr/bin/shellspec

        '
    - continue-on-error: true
      name: Install dependencies
      run: dnf install -y ed bc diffutils
    - continue-on-error: true
      name: Run shellspec
      run: 'cd tests/shell

        shellspec

        '
  shellspec-ubuntu:
    name: Ubuntu
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install shellspec
      run: curl -fsSL https://git.io/shellspec | sh -s ${{ env.SHELLSPEC_VERSION }}
        --yes
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Run Shellspec
      run: 'cd tests/shell

        shellspec

        '
name: Shellspec
on:
  repository_dispatch:
    types: trigger-ga___shellspec.yml
