jobs:
  shellcheck:
    name: Shellcheck
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: shellcheck
      uses: reviewdog/action-shellcheck@v1
      with:
        exclude: '*/.git/*

          doc/*

          downloads/*

          scripts/database/*

          scripts/globalid/*

          scripts/icons/*

          scripts/installer/*

          scripts/issues/*

          scripts/r/*

          scripts/tests/*

          tests/*

          '
        fail_on_error: true
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        shellcheck_flags: --shell=bash --external-sources
name: Shellcheck
on:
  repository_dispatch:
    types: trigger-ga___shellcheck.yml
